# Generated by Django 3.2.9 on 2022-03-01 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_auto_20220301_1234'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='specialistconsultancy',
        #     name='specialist_DoctorassignedBy',
        # ),
        # migrations.RemoveField(
        #     model_name='specialistconsultancy',
        #     name='specialist_docpatient',
        # ),
        # migrations.RemoveField(
        #     model_name='specialistconsultancy',
        #     name='specialist_patientLabTestreport',
        # ),
        # migrations.DeleteModel(
        #     name='phcConsultancy',
        # ),
        # migrations.DeleteModel(
        #     name='specialistConsultancy',
        # ),
    ]
