# Generated by Django 3.2.9 on 2022-03-01 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0003_auto_20220301_1238'),
    ]

    operations = [
        #migrations.DeleteModel(
        #    name='phcConsultancy',
        #),
    ]
