# Generated by Django 3.2.9 on 2022-03-01 12:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0004_delete_phcconsultancy'),
    ]

    operations = [
        migrations.CreateModel(
            name='specialistConsultancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialist_isPending', models.BooleanField(default=True)),
                ('specialist_isMedication', models.BooleanField(default=False)),
                ('specialist_isHospitalisation', models.BooleanField(default=False)),
                ('specialist_Consultation', models.BooleanField(default=False)),
                ('specialist_isElderline', models.BooleanField(default=False)),
                ('specialist_suggestion_type', models.CharField(blank=True, max_length=500, null=True)),
                ('specialist_ConsultationDate', models.DateTimeField(blank=True, null=True)),
                ('suggestion_type', models.CharField(blank=True, max_length=500, null=True)),
                ('specialist_medicationDate', models.DateTimeField(blank=True, null=True)),
                ('specialist_phcConsultationDate', models.DateTimeField(blank=True, null=True)),
                ('specialist_hospitalisationDate', models.DateTimeField(blank=True, null=True)),
                ('specialist_elderlineDate', models.DateTimeField(blank=True, null=True)),
                ('specialist_medicationClosedDate', models.DateTimeField(blank=True, null=True)),
                ('specialist_phcConsultationClosedDate', models.DateTimeField(blank=True, null=True)),
                ('specialist_hospitalisationClosedDate', models.DateTimeField(blank=True, null=True)),
                ('specialist_elderlineClosedDate', models.DateTimeField(blank=True, null=True)),
                ('specialist_medicationRemarks', models.CharField(blank=True, max_length=500, null=True)),
                ('specialist_hospitalizationRemarks', models.CharField(blank=True, max_length=500, null=True)),
                ('specialist_consultationphcRemarks', models.CharField(blank=True, max_length=500, null=True)),
                ('specialist_elderlineRemarks', models.CharField(blank=True, max_length=500, null=True)),
                ('specialist_fileUpload', models.FileField(blank=True, upload_to='doctorFolder')),
                ('specialist_appointDate', models.DateField(blank=True, null=True)),
                ('specialist_appointTime', models.TimeField(blank=True, null=True)),
                ('specialist_isCaseClosed', models.BooleanField(default=False)),
                ('specialist_caseClosedDate', models.DateTimeField(blank=True, null=True)),
                ('specialist_created_date', models.DateTimeField(auto_now_add=True)),
                ('specialist_DoctorassignedBy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='specialistDoctorassignedBy', to=settings.AUTH_USER_MODEL)),
                ('specialist_docpatient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='specialistDoctorConsultancy', to='database.familymembers')),
                ('specialist_patientLabTestreport', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='specialistPatientLabTestreport', to='database.patienttest')),
            ],
        ),
        migrations.CreateModel(
            name='phcConsultancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isPending', models.BooleanField(default=True)),
                ('isMedication', models.BooleanField(default=False)),
                ('isHospitalisation', models.BooleanField(default=False)),
                ('phcConsultation', models.BooleanField(default=False)),
                ('isElderline', models.BooleanField(default=False)),
                ('suggestion_type', models.CharField(blank=True, max_length=500, null=True)),
                ('medicationDate', models.DateTimeField(blank=True, null=True)),
                ('phcConsultationDate', models.DateTimeField(blank=True, null=True)),
                ('hospitalisationDate', models.DateTimeField(blank=True, null=True)),
                ('elderlineDate', models.DateTimeField(blank=True, null=True)),
                ('medicationClosedDate', models.DateTimeField(blank=True, null=True)),
                ('phcConsultationClosedDate', models.DateTimeField(blank=True, null=True)),
                ('hospitalisationClosedDate', models.DateTimeField(blank=True, null=True)),
                ('elderlineClosedDate', models.DateTimeField(blank=True, null=True)),
                ('medicationRemarks', models.CharField(blank=True, max_length=500, null=True)),
                ('hospitalizationRemarks', models.CharField(blank=True, max_length=500, null=True)),
                ('consultationphcRemarks', models.CharField(blank=True, max_length=500, null=True)),
                ('elderlineRemarks', models.CharField(blank=True, max_length=500, null=True)),
                ('fileUpload', models.FileField(blank=True, upload_to='doctorFolder')),
                ('appointDate', models.DateField(blank=True, null=True)),
                ('appointTime', models.TimeField(blank=True, null=True)),
                ('isCaseClosed', models.BooleanField(default=False)),
                ('caseClosedDate', models.DateTimeField(blank=True, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('docpatient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='phcDoctorConsultancy', to='database.familymembers')),
                ('patientLabTestreport', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='phcPatientLabTestreport', to='database.patienttest')),
            ],
        ),
    ]
