# Generated by Django 3.2.9 on 2022-03-02 05:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0005_phcconsultancy_specialistconsultancy'),
    ]

    operations = [
        migrations.AddField(
            model_name='phcconsultancy',
            name='phcDoctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='phcConsultancyPhcDoctor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='specialistconsultancy',
            name='specialistDoctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='specialistConsultancySpecialistDoctor', to=settings.AUTH_USER_MODEL),
        ),
    ]
