# Generated by Django 3.2.9 on 2022-03-07 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0006_auto_20220302_0549'),
    ]

    operations = [
        migrations.AddField(
            model_name='familymembers',
            name='member_dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='phcconsultancy',
            name='consultationFileUpload',
            field=models.FileField(blank=True, upload_to='doctorFolder'),
        ),
        migrations.AddField(
            model_name='specialistconsultancy',
            name='specialist_consultationFileUpload',
            field=models.FileField(blank=True, upload_to='doctorFolder'),
        ),
    ]
