# Generated by Django 3.2.9 on 2022-03-15 04:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0007_auto_20220307_0419'),
    ]

    operations = [
        migrations.AddField(
            model_name='familymembers',
            name='claimedBy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='familyMembers_claimedBy', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='familymembers',
            name='isClaimed',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='SurveyourAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district', models.CharField(blank=True, max_length=100, null=True)),
                ('region_type', models.CharField(blank=True, max_length=50, null=True)),
                ('municipal_corporation', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('ward', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('municipal_council', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('taluka', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('phc', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('addressOfSurveyor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='SurveyourAddress_surveyor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
