# Generated by Django 3.2.9 on 2022-04-21 10:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0008_auto_20220315_0456'),
    ]

    operations = [
   
    ]
