# Generated by Django 3.2.9 on 2022-04-21 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0009_familymembers_claimedby'),
    ]

    operations = [
      
    ]
